name: Validate team permission
description: Deploy resource version on argoCD.
inputs:
  team_name:
    description: "The team name to validate permission for"
    required: true

runs:
  using: composite
  steps:
    - name: Validate team permission
      uses: actions/github-script@v7
      with:
        team_name: ${{ inputs.team_name }}
        script: |
          const teamName = core.getInput('team_name');

          const { data } = await github.rest.teams.listMembersInOrg({
            org: "redislabsdev",
            team_slug: teamName,
          });

          console.log(`Checking team permission for ${context.actor}`);

          console.log(
            `Team members of ${teamName} are: ${data.map((user) => user.login).join(", ")}`
          );

          const isUserIncludedInTeam = data.some(
            (user) => user.login === context.actor
          );

          if (!isUserIncludedInTeam) {
            throw new Error(
              `GitHub user: ${context.actor} is not part of ${teamName} and cannot run this workflow`
            );
          }
