name: Deploy cloud ui module version to staging or production

on:
  push:
    paths:
      - "environments/cloud-k8s-prod/sm-prod/cloud-ui-modules/**.json"
      - "environments/cloud-k8s-staging/sm-staging/cloud-ui-modules/**.json"
    branches:
      - "test-deploy"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18.12.1
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v38
        with:
          separator: ","
          files: "**/cloud-ui-modules/*.json"
      - name: Get changed files
        run: echo "CHANGED_FILES=${{ steps.changed-files.outputs.all_changed_files }}" >> $GITHUB_ENV
      - name: Deploy
        run: node ./.github/workflows/cloud-ui-deploy-scripts/deploy.js
