name: Visual Tests
on:
  pull_request:
    types:
      - opened  
      - synchronize  
      - reopened  
      - unlabeled  
jobs:
  visual-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'
        registry-url: https://npm.pkg.github.com
    - name: Test run
      if: 'asdasd' != ''
      run: |
        npm install
        npm run test:visual
    
    