name: Testing something
on:
  pull_request:
    branches:
      - main
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://registry.npmjs.org"
      - name: View context attributes
        uses: actions/github-script@v7
        with:
          script: console.log(context)
      - uses: ./.github/workflows/publish.yml
